# Generated by Django 4.2.1 on 2024-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='salesman',
            field=models.CharField(default='', max_length=100, verbose_name='Salesman'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='type',
            field=models.CharField(default='', max_length=30, verbose_name='Type'),
        ),
    ]
