# Generated by Django 4.2.1 on 2024-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_productmodel_salesman_productmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(max_length=10, verbose_name='count size')),
                ('m', models.CharField(max_length=10, verbose_name='count size')),
                ('l', models.CharField(max_length=10, verbose_name='count size')),
                ('xl', models.CharField(max_length=10, verbose_name='count size')),
                ('xxl', models.CharField(max_length=10, verbose_name='count size')),
            ],
            options={
                'verbose_name': 'ClothSize',
                'verbose_name_plural': 'ClothSizes',
            },
        ),
        migrations.CreateModel(
            name='SalesMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Salesman Name')),
                ('countofmany', models.CharField(max_length=200, verbose_name='CountOfMoney')),
                ('descript', models.TextField(max_length=300, verbose_name='Descript')),
                ('mail', models.EmailField(max_length=40, verbose_name='Mail')),
                ('grade', models.CharField(max_length=1, verbose_name='greade')),
            ],
            options={
                'verbose_name': 'Salesman',
                'verbose_name_plural': 'Salesmans',
            },
        ),
        migrations.CreateModel(
            name='Snikers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size35', models.CharField(max_length=10, verbose_name='count size')),
                ('size36', models.CharField(max_length=10, verbose_name='count size')),
                ('size37', models.CharField(max_length=10, verbose_name='count size')),
                ('size38', models.CharField(max_length=10, verbose_name='count size')),
                ('size39', models.CharField(max_length=10, verbose_name='count size')),
                ('size40', models.CharField(max_length=10, verbose_name='count size')),
                ('size41', models.CharField(max_length=10, verbose_name='count size')),
                ('size42', models.CharField(max_length=10, verbose_name='count size')),
                ('size43', models.CharField(max_length=10, verbose_name='count size')),
                ('size44', models.CharField(max_length=10, verbose_name='count size')),
                ('size45', models.CharField(max_length=10, verbose_name='count size')),
            ],
            options={
                'verbose_name': 'SnikersSize',
                'verbose_name_plural': 'SnikersSizes',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='linkToSize',
            field=models.CharField(default='', max_length=30, verbose_name='Link'),
        ),
    ]
