# Generated by Django 4.2.3 on 2024-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_cloth_salesman_snikers_productmodel_linktosize'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='password',
            field=models.CharField(default='', max_length=15, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='salesman_img',
            field=models.ImageField(blank=True, default='use.jpeg', null=True, upload_to='images/'),
        ),
    ]
