# Generated by Django 4.2.3 on 2024-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_salesman_password_salesman_salesman_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='user_img',
            field=models.ImageField(blank=True, default='USERS.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='password',
            field=models.CharField(default='1111', max_length=15, verbose_name='Password'),
        ),
    ]
