# Generated by Django 4.2.3 on 2024-04-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_salesman_indif'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=100, verbose_name='Count')),
                ('indif', models.CharField(default='', max_length=100, verbose_name='Индификатор')),
            ],
            options={
                'verbose_name': 'Count',
                'verbose_name_plural': 'Counts',
            },
        ),
        migrations.AddField(
            model_name='cloth',
            name='indif',
            field=models.CharField(default='', max_length=100, verbose_name='Индификатор'),
        ),
        migrations.AddField(
            model_name='snikers',
            name='indif',
            field=models.CharField(default='', max_length=100, verbose_name='Индификатор'),
        ),
    ]
