# Generated by Django 4.2.3 on 2024-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_countproduct_cloth_indif_snikers_indif'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='salerName',
            field=models.CharField(default='', max_length=30, verbose_name='Salesman Name'),
        ),
    ]
