# Generated by Django 4.2.3 on 2024-04-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_salesman_salername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snikers',
            name='size35',
        ),
    ]
